- name: Get kernel release
  shell: uname -r
  register: kernel_release
  changed_when: false
- name: Install linux image extra
  sudo: yes
  apt:
    name: linux-image-extra-{{ kernel_release.stdout }}
    state: latest
- name: Add new gpg key for docker
  sudo: yes
  apt_key:
    keyserver: "hkp://pgp.mit.edu:80"
    id: 58118E89F3A912897C070ADBF76221572C52609D
    state: present
- name: Set docker.list for apt
  sudo: yes
  template:
    dest: /etc/apt/sources.list.d/docker.list
    src: docker.list.j2
    force: yes
- name: Update apt
  sudo: yes
  apt:
    upgrade: safe
    update_cache: yes
    state: latest
- name: Install docker
  sudo: yes
  apt:
    name: docker-engine
    state: latest

